languageCode = "en-us"
title = "Mr Waterbed NZ"
baseurl = "/"
description = "Waterbed Sales and Servicing"
keywords = "waterbeds beds sales conditioner leaks repairs moving parts"
content = "Sales of waterbed products NZ wide, as well as, sales and service in the greater Wellington area"
googleAnalyticsId = "UA-33387443-1"
